{
 "title": "State-Grid SpringBoot",
 "tags": [
  "state-grid",
  "springboot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "应用是否在线",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"state-grid-app\"}"
    }
   ]
  },
  {
   "title": "JVM 已用堆内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"state-grid-app\",area=\"heap\"}",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  {
   "title": "HTTP 请求耗时(秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"state-grid-app\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}