worker_processes 1;
events { worker_connections 1024; }
http {
    upstream exam_app {
        server host.docker.internal:8080;
        server host.docker.internal:8081 backup;
    }
    upstream blade_app {
        server host.docker.internal:9999;
    }
    server {
        listen 80;
        location /blade-auth/ {
            proxy_set_header Host $host;
            proxy_pass http://blade_app/blade-auth/;
        }
        location /blade-user/ {
            proxy_set_header Host $host;
            proxy_pass http://blade_app/blade-user/;
        }
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://exam_app;
        }
        location /actuator/ {
            proxy_set_header Host $host;
            proxy_pass http://exam_app/actuator/;
        }
    }
}
