spring:
  application:
    name: rocketmq-provider

rocketmq:
  name-server: 192.168.150.130:9876
  producer:
    group: producer-group
    send-message-timeout: 50000
    vip-channel-enabled: false
server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: '*'