book.name=QQQ
book.author=WWW
# 随机字符串UUID
rand.aaa=${random.value}
# 随机int
rand.bbb=${random.int}
# 10以内的随机int
rand.ccc=${random.int(10)}
# 10-20的随机int
rand.ddd=${random.int[10,20]}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload.path=D:\\upload