# 开发环境配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: exam-demo

remote:
  auth:
    token-url: http://localhost:9999/blade-auth/token
    user-list-url: http://localhost:9999/blade-user/user-list
    client-id: saber
    client-secret: saber_secret
    tenant-id: "000000"
    username: admin
    password: "21232f297a57a5a743894a0e4a801fc3"
    grant-type: password
    type: account
    scope: all

minio:
  endpoint: http://127.0.0.1:9000
  access-key: remote_user
  secret-key: 0123456789.abcdefg
  bucket: demo
