
spring:
    datasource:
        #说明：如果没有指定useSSL=true，启动项目可能会爆红警告,环境问题
        url: jdbc:mysql://localhost:3306/ry-vue?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver