server:
  port: 8060
spring:
  application:
    name: openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.130:8848

logging:
  level:
    com.springcloud.openfeign: debug

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
