worker_processes 1;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $host "$request" $status';
    access_log /var/log/nginx/access.log main;

    upstream state_grid_app {
        least_conn;
        server host.docker.internal:8080;
        server host.docker.internal:8081 backup;
    }

    upstream blade_mock {
        server host.docker.internal:18080;
    }

    server {
        listen 80;
        server_name localhost;

        location /blade-auth/ {
            proxy_pass http://blade_mock;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /blade-user/ {
            proxy_pass http://blade_mock;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://state_grid_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
