USE ops_demo;

DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT (
    ID       BIGINT      PRIMARY KEY,
    NAME     VARCHAR(20) NOT NULL,
    LOCATION VARCHAR(100)

CREATE TABLE EMP (
    ID      BIGINT       PRIMARY KEY,
    NAME    VARCHAR(100) NOT NULL,
    SALARY  INT,
    DEPTID  INT,
    CONSTRAINT fk_emp_dept FOREIGN KEY (DEPTID) REFERENCES DEPT (ID)

INSERT INTO DEPT (ID, NAME, LOCATION) VALUES
(1, '研发部', '一楼'),
(2, '人事部', '二楼');

INSERT INTO EMP (ID, NAME, SALARY, DEPTID) VALUES
(1001, '张三', 5000, 1),
(1002, '李四', 4000, 1),
(1003, '王五', 1000, 2),
(1004, '赵六', 3000, 2);

-- 1. 更新员工表数据，将张三的薪水提升10%
UPDATE EMP SET SALARY = SALARY * 1.1 WHERE NAME = '张三';

-- 2. 查询所有姓王的员工，并按照薪水降序
SELECT * FROM EMP WHERE NAME LIKE '王%' ORDER BY SALARY DESC;

-- 3. 查询员工表，只显示第2-4条记录
SELECT * FROM EMP LIMIT 1, 3;

-- 4. 用左外连接查询所有的员工以及其部门信息
SELECT e.ID, e.NAME, e.SALARY, e.DEPTID, d.NAME AS DEPT_NAME, d.LOCATION
FROM EMP e
LEFT JOIN DEPT d ON e.DEPTID = d.ID;

-- 5. 查询各部门的人数
SELECT d.ID, d.NAME, COUNT(e.ID) AS emp_count
FROM DEPT d
LEFT JOIN EMP e ON d.ID = e.DEPTID
GROUP BY d.ID, d.NAME;

-- 6. 查询平均薪水大于3000的部门
SELECT d.ID, d.NAME, AVG(e.SALARY) AS avg_salary
GROUP BY d.ID, d.NAME
HAVING AVG(e.SALARY) > 3000;
