server:
  port: 8080

spring:
  application:
    name: state-grid-app
  datasource:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

remote:
  oauth:
    url: http://127.0.0.1:18080/blade-auth/token
    client-id: saber
    client-secret: saber_secret
    tenant-id: "000000"
    username: admin
    password: 21232f297a57a5a743894a0e4a801fc3
    grant-type: password
    type: account
    scope: all
  user:
    url: http://127.0.0.1:18080/blade-user/user-list
    page-size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
