CREATE DATABASE IF NOT EXISTS blade DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS state_grid DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS ops_demo DEFAULT CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'hjx127307';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';
FLUSH PRIVILEGES;
